# databasedotcom.yml
#
---
# Sandbox EV
client_secret: '3261162599500258133'
client_id: '3MVG9Gmy2zmPB01rlpzY39G2MTkUYUIaKmxVeMPWjR1BUJvhC5v8fTwdX0oG9KWOXisBCJwa2ATBjZUoA4wFA'
# dedicated ORG Oxala
#client_secret: '8086027360834568335'
#client_id: '3MVG9QDx8IX8nP5RirhqQ1R8GjMpb7AFTFW5nuMKiw7eGYugiyRPrBHHrHRIcMPHu2caVhuwjb2fBmuGWMZQs'
#client_id: '3MVG9PhR6g6B7ps6in8a_o8S1Ip1iiDMK828FkdlmF4XnBbv9Ek6CXfSjQzji5eJimP4yOWPS76bmJcZidCFP'
#client_secret: '2041292024636461725'

